global:
  image: {}
  openfaas: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-function-history-report"
  # repository: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

resources:
  requests:
    cpu: 50m
    memory: 30Mi
  limits:
    cpu: 100m

# used to generate registry api base url
registryApiVersion: "v0"
authApiVersion: "v0"

tenantId: 0

# Set a list of secrets that pass to function
# Secrets are accessible from `/var/openfaas/secrets/<secret-name>` as file
secrets:
- auth-secrets