# More exmaples of openfaas function here: https://github.com/openfaas/openfaas-operator
{{- if .Values.global.openfaas.enabled | default false | ne true }}
{{- required "`magda-function-history-report` requires `magda-core`.`openfaas` to deploy. Please turn on openfaas by setting `global.openfaas.enabled` to `true` or turn off `magda-function-history-report` to avoid this error." nil }}
{{- else }}
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ include "magda-function-history-report.openfaasFunctionNamespace" . | quote }}
spec:
  name: {{ .Chart.Name }}
  handler: node bootstrap.js
  image: {{ include "magda.image" . | quote }}
  labels: 
    com.openfaas.scale.zero: "true"
    # You can add any other labels to help the caller to tell the purpose of the functions
    magdaType: general-purpose-function
  annotations:
    com.openfaas.health.http.path: "/healthz"
    com.openfaas.health.http.initialDelay: "10s"
  environment:
    read_timeout: 65s
    write_timeout: 65s
    exec_timeout: 60s
    tenantId: {{ .Values.tenantId | quote }}
    registryApiUrl: {{ include "magda-function-history-report.registryApiUrl" . | quote }}
    authApiUrl: {{ include "magda-function-history-report.authApiUrl" . | quote }}
  {{- $pullSecrets := include "magda.image.getConsolidatedPullSecretList" . | mustFromJson }}
  {{- if and (.Values.secrets | empty | not) (kindIs "slice" .Values.secrets) }}
    {{- $pullSecrets = concat $pullSecrets .Values.secrets }}
  {{- end }}
  {{- if (not (empty $pullSecrets)) }}
  secrets: 
    {{- range $pullSecrets }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{ .Values.resources | toYaml | indent 2 -}}
{{- end }}
